# Generated by Django 5.2.7 on 2025-10-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='estado',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Usada', 'Usada')], default='Nueva', max_length=5),
        ),
        migrations.AddField(
            model_name='moto',
            name='kilometros',
            field=models.IntegerField(default=0),
        ),
    ]
